INSERT INTO SOMETHING(name) VALUES('test0')
INSERT INTO SOMETHING(name) VALUES('test1')
INSERT INTO SOMETHING(name) VALUES('test2')
INSERT INTO SOMETHING(name) VALUES('test3')
INSERT INTO SOMETHING(name) VALUES('test4')
INSERT INTO SOMETHING(name) VALUES('test5')
INSERT INTO SOMETHING(name) VALUES('test6')
INSERT INTO SOMETHING(name) VALUES('test7')
INSERT INTO SOMETHING(name) VALUES('test8')
INSERT INTO SOMETHING(name) VALUES('test9')

INSERT INTO ING_USER (id, password) VALUES ('user1', 'pass1');
INSERT INTO ING_USER (id, password) VALUES ('user2', 'pass1');
INSERT INTO ING_USER (id, password) VALUES ('user3', 'pass1');
INSERT INTO ING_USER (id, password) VALUES ('user4', 'pass1');
